apiVersion: apps/v1
kind: Deployment
metadata:
     name: guestbook-ui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          name: guestbook-ui
          resources:
           requests:
             memory: "256Mi"
             cpu: "250m"
           limits:
             memory: "250Mi"
             cpu: "1"
          ports:
            - containerPort: 80
